on: push

jobs:
  approve-prs:
    runs-on: ubuntu-latest
    name: Approve valid PRs on cadence
    steps:
      - name: Approve valid workflows
        uses: Cian911/gomerge-action@v1
        with:
          repository: ${{ github.repository }}
          github_token: ${{ github.token }}
          approve: "true"
