on: push

jobs:
  approve-prs:
    runs-on: ubuntu-latest
    name: Approve valid PRs 
    steps:
      - name: Approve valid workflows
        uses: Cian911/gomerge-action@master
        with:
          args:
            - ${{ github.repository }}
            - ${{ secrets.GITHUB_TOKEN }}
            - ""
            - "true"
